# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ab55bbbe4997c4e72573adfafc7b650c8167bdd77cad62515e73efa0f4d879fa8db1c6408d8e4631ab54183394e8d05595494b5b6679da8edb9bb22e2450832

test:
  secret_key_base: 4248df4ef0738bcdb9b23936b2955196d5705bfaa975f7eb5977b24b2ecf858eb6b57781b4eeed85ba297138f74e9a214f17e7467308dca38c2327fc3e871de2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
